M48
; DRILL file {KiCad (6.0.9)} date Sat Feb  4 16:03:48 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-04T16:03:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X104.0Y-64.0
X104.0Y-146.0
X181.0Y-64.0
X181.0Y-146.0
T2
X167.5Y-78.0
X167.5Y-132.0
T2
X152.5Y-104.0G85X152.5Y-108.0
G05
T0
M30
