M48
; DRILL file {KiCad (6.0.9)} date Fri Jan 27 22:09:56 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-27T22:09:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X103.902Y-63.854
X103.902Y-145.854
X180.902Y-63.854
X180.902Y-145.854
T0
M30
